# LINUS-APPROVED TRADING SYSTEM CONFIG
# NO MAGIC NUMBERS. EVERY PARAMETER IS HERE.

# Core System
system:
  name: "SimpleTradingSystem"  # Not "SAFLA Neural Consciousness Engine"
  version: "1.0.0"
  random_seed: 42
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR

# Exchange Configuration
exchange:
  name: "binance"
  sandbox: true  # Use testnet until proven working
  rate_limit_per_minute: 1200
  timeout_seconds: 30
  retry_attempts: 3
  retry_delay_seconds: 1

  # Circuit breaker settings for resilience
  circuit_breaker:
    failure_threshold: 5      # Open after 5 consecutive failures
    recovery_timeout: 30.0    # Try recovery after 30 seconds
    success_threshold: 3      # Close after 3 successful recovery attempts

# Multi-Exchange Configuration (for enhanced trading system)
exchanges:
  binance:
    sandbox: true              # Use testnet/sandbox mode
    rate_limit_ms: 1000        # Rate limit in milliseconds
    timeout_ms: 30000          # Timeout in milliseconds
    # API credentials (use environment variables for security)
    # api_key: "your_api_key_here"     # Or set BINANCE_API_KEY env var
    # secret: "your_secret_here"       # Or set BINANCE_SECRET env var
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: 30.0
      success_threshold: 3

  kraken:
    sandbox: true
    rate_limit_ms: 1000
    timeout_ms: 30000
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: 30.0
      success_threshold: 3

  bybit:
    sandbox: true
    rate_limit_ms: 1000
    timeout_ms: 30000
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout: 30.0
      success_threshold: 3

# Trading Symbols
symbols:
  primary: ["BTC/USDT", "ETH/USDT"]
  test: ["BTC/USDT"]  # Start with one symbol

# Market Data
market_data:
  timeframe: "1h"  # Use hourly candles for demo
  lookback_candles: 200  # Increased for better SMA calculation
  fetch_limit: 1000  # Max candles per request

# Simulation Parameters
simulation:
  initial_balance_usd: 100000.0
  commission_rate: 0.001  # 0.1% per trade (realistic for Binance)

  # Slippage simulation (because markets aren't perfect)
  slippage:
    base_bps: 1  # 1 basis point base slippage
    impact_coefficient: 0.1  # Additional slippage per $1000 trade
    max_slippage_bps: 10  # Cap at 10 bps

# Strategy Configuration - Simple Moving Average Crossover
strategy:
  type: "sma_crossover"

  # Moving average periods - OPTIMIZED FOR HOURLY DATA
  fast_period: 5   # Reduced from 10 for more responsive signals
  slow_period: 20  # Reduced from 30 for hourly timeframe

  # Signal thresholds - REDUCED FOR CRYPTO VOLATILITY
  entry_threshold_pct: 0.002  # 0.2% crossover minimum (was 1%)
  exit_threshold_pct: 0.001   # 0.1% exit signal (was 0.5%)

  # Position sizing
  position_size_pct: 0.10  # 10% of balance per trade
  max_position_size_usd: 10000  # Hard cap per position

# Risk Management (The Important Stuff)
risk:
  # Position limits
  max_open_positions: 3
  max_portfolio_exposure_pct: 0.50  # 50% max exposure

  # Stop losses
  stop_loss_pct: 0.02  # 2% stop loss
  take_profit_pct: 0.04  # 4% take profit (2:1 ratio)

  # Daily limits
  max_daily_loss_pct: 0.05  # 5% daily loss limit
  max_daily_trades: 10

  # Portfolio protection
  max_drawdown_pct: 0.10  # 10% max drawdown

# Logging Configuration (Proper Logging)
logging:
  # Log levels: trades, market_data, decisions, performance, errors

  # File destinations
  files:
    trades: "logs/trades.jsonl"
    market_data: "logs/market_data.jsonl"
    decisions: "logs/decisions.jsonl"
    performance: "logs/performance.jsonl"
    errors: "logs/errors.jsonl"

  # Rotation settings
  max_file_size_mb: 100
  backup_count: 10

  # What to log
  log_every_tick: false  # Would be too much for 1m data
  log_every_decision: true
  log_every_trade: true
  log_performance_interval_seconds: 60

# Performance Metrics
metrics:
  # Calculation windows (in number of trades)
  sharpe_ratio_window: 30
  win_rate_window: 20
  max_drawdown_window: 100

  # Reporting intervals
  report_interval_trades: 10

# Data Storage
storage:
  # Market data cache
  cache_directory: "data/cache"
  cache_retention_days: 30

  # Trade history
  trade_history_file: "data/trade_history.csv"

  # Performance tracking
  performance_file: "data/performance.csv"

# Testing Configuration
testing:
  # Backtesting parameters
  start_date: "2024-01-01"
  end_date: "2024-12-31"

  # Paper trading
  paper_trading: true

  # Test data generation
  generate_test_data: false
  test_data_days: 7

# Alert Thresholds (When Things Go Wrong)
alerts:
  # Portfolio alerts
  drawdown_alert_pct: 0.05  # Alert at 5% drawdown
  daily_loss_alert_pct: 0.03  # Alert at 3% daily loss

  # System alerts
  error_count_threshold: 5  # Alert after 5 errors
  connection_timeout_threshold: 10  # Alert after 10 timeouts

# Neural System Configuration (SAFLA Components)
neural:
  # Network architecture
  input_dim: 64
  output_dim: 8
  hidden_dim: 128
  dropout_rate: 0.1
  learning_rate: 0.001

  # Training thresholds
  accuracy_threshold_low: 0.3  # Trigger immediate adaptation
  accuracy_threshold_high: 0.8  # Success feedback threshold
  loss_threshold_high: 5.0     # Error feedback threshold
  loss_threshold_normal: 1.0   # Normal loss threshold

  # Confidence and uncertainty
  confidence_threshold: 0.6    # Minimum confidence for decisions
  uncertainty_threshold: 0.5   # Maximum uncertainty allowed

  # Performance stability
  performance_window_size: 100 # Recent performance deque size
  stability_min_samples: 10    # Minimum samples for stability calculation

# Feedback System Configuration
feedback:
  # Learning cycles
  cycle_timeout_seconds: 3600  # 1 hour timeout for learning cycles
  max_feedback_buffer: 1000    # Maximum feedback signals to buffer

  # Feedback thresholds
  error_feedback_threshold: 0.8    # High error signal threshold
  success_feedback_threshold: 0.8  # High success signal threshold
  performance_feedback_min: 0.5    # Minimum for performance feedback

  # Analysis parameters
  trend_analysis_window: 50     # Window for trend analysis
  pattern_analysis_samples: 20  # Samples for pattern analysis

# Self-Improvement Configuration
improvement:
  # Candidate selection
  min_confidence: 0.6          # Minimum confidence for implementation
  min_impact_estimate: 0.05    # Minimum estimated impact
  max_candidates_per_cycle: 3  # Maximum improvements per cycle

  # Optimization parameters
  parameter_adjustment_factor: 0.2  # Learning rate adjustment factor
  architecture_growth_factor: 2.0   # Hidden layer size multiplier
  rollback_failure_threshold: 0.3   # Performance drop for rollback

  # Meta-learning
  meta_learning_rate: 0.01     # Rate for meta-parameter updates
  adaptation_frequency_limit: 5 # Max adaptations per hour

# Coordination Configuration
coordination:
  # Background processing
  coordination_interval_seconds: 60  # Coordination loop interval
  health_check_interval: 300         # Health monitoring interval

  # Threading
  max_worker_threads: 4              # Maximum background threads
  thread_timeout_seconds: 30         # Thread operation timeout

  # Memory management
  memory_optimization_interval: 600  # Memory cleanup interval
  memory_usage_threshold: 0.8       # Memory usage alert threshold

# Memory System Configuration
memory:
  # Vector memory
  vector_dimension: 128         # Vector embedding dimension
  vector_max_entries: 10000     # Maximum vector entries

  # Episodic memory
  episodic_max_entries: 50000   # Maximum episodic entries
  episodic_similarity_threshold: 0.5  # Similarity for related episodes

  # Semantic memory
  semantic_max_entries: 10000   # Maximum semantic entries
  knowledge_graph_max_depth: 3  # Maximum relationship traversal depth

  # Working memory
  working_memory_context_window: 100  # Context window size
  working_memory_max_entries: 1000    # Maximum working memory entries
  attention_weight_threshold: 0.7     # Minimum attention weight

  # Compression settings
  compression_ratio_target: 0.6       # Target compression ratio
  importance_threshold_low: 0.2       # Low importance cleanup threshold

  # Persistence settings
  persistence_enabled: true           # Enable persistent storage
  storage_directory: "data/memory"    # Base directory for memory storage
  vector_cache_file: "vectors.pkl"    # Vector memory cache file
  episodic_db_file: "episodic.db"     # Episodic memory SQLite database
  semantic_cache_file: "semantic.pkl" # Semantic memory cache file
  auto_save_interval: 300             # Auto-save interval in seconds

# Development Settings
development:
  debug_mode: false
  profiling_enabled: false
  test_mode: true  # Extra validation and checks